### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by amazing-gao** [shramov/json2pb#3]
# leak 1:

static json_t \* _field2json(const Message& msg, const FieldDescriptor *field, size_t index)
{
    ...
    json_t *jf = 0;
    json_autoptr jf_ptr(jf);     // use json_autoptr, line 52
    ...
}
# leak 2:

static json_t \* _pb2json(const Message& msg)
{
         json_t *jf = 0;
        json_autoptr jf_ptr(jf);     //the same bug, line 121
}

**Comment by mhaberler** [comment]
why dont you post a PR?
