### ISSUE TITLE
pb2json.py generates floats which are not properly parsed by pb2json.cc

### ISSUE THREAD

**Issue by mhaberler** [shramov/json2pb#4]
a float may come out looking like an int, which trips pb2json.cc parsing: 

json2pb exception: y: Failed to unpack: Expected real, got integer

**Comment by amazing-gao** [comment]
i found this bug too.
i modify json2pb.cc line 170
        _CONVERT(CPPTYPE_INT64, json_int_t, "F", SetInt64, AddInt64);
        _CONVERT(CPPTYPE_UINT64, json_int_t, "F", SetUInt64, AddUInt64);

it's ok to parse float
